name: build
on: [push, pull_request]
jobs:
  build:
    env:
      # The special value "local" tells Go to use the bundled Go
      # version rather than trying to fetch one according to a
      # `toolchain` value in `go.mod`. This ensures that we're
      # really running the Go version in the CI matrix rather than
      # one that the Go command has upgraded to automatically.
      GOTOOLCHAIN: local
    strategy:
      matrix:
        go-version: [x.x.x]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
        id: go

      - name: Build
        run: go build -v -o webhook__${{ matrix.os }}

      - name: Test
        run: go test -v ./...

      - name: Build cross compile
        run: env GOOS=linux GOARCH=arm64 go build -o webhook_${{ matrix.os }}_arm64

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.4.3
        with:
          # A file, directory or wildcard pattern that describes what to upload
          path: webhook*
          name: webhook_${{ matrix.os }}.zip
