name: build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        go-version: [x.x.x]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
        id: go

      - name: Build
        run: go build -v

      - name: Test
        run: go test -v ./...

  build-arm:
    strategy:
      matrix:
        go-version: [x.x.x]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
          architecture: arm64
        id: go

      - name: Build
        run: go build -v

      - name: Test
        run: go test -v ./...
